"""Canonical domain types used independently of upstream FPL payloads."""

from gaffertalk_api.domain.models import (
    Club,
    DataProvenance,
    EntrySummary,
    Fixture,
    FplCatalogue,
    GameRules,
    Gameweek,
    Money,
    Player,
    Position,
    SquadAvailability,
    SquadAvailabilityStatus,
    SquadLookupResult,
    SquadPick,
    SquadSnapshot,
)
from gaffertalk_api.domain.transfers import (
    ProposedTransfer,
    TransferLegalityResult,
    TransferLegalityStatus,
    TransferPlanningState,
    TransferRejection,
    TransferRejectionCode,
)

__all__ = [
    "Club",
    "DataProvenance",
    "EntrySummary",
    "Fixture",
    "FplCatalogue",
    "GameRules",
    "Gameweek",
    "Money",
    "Player",
    "Position",
    "SquadAvailability",
    "SquadAvailabilityStatus",
    "SquadLookupResult",
    "SquadPick",
    "SquadSnapshot",
    "ProposedTransfer",
    "TransferLegalityResult",
    "TransferLegalityStatus",
    "TransferPlanningState",
    "TransferRejection",
    "TransferRejectionCode",
]
